### ISSUE TITLE
POSTs fail with NoMethodError: undefined method `join' for #<String.....>

### ISSUE THREAD

**Issue by dquenault** [arr2036/omnigollum#29]
Has anyone had issues with POST requests in omnigollum?  I've got multiple providers working and logging in is working correctly. However, if I run a create/edit/history POST I get a String.join error. If I run the same wiki in the same environment without omnigollum (gollum by itself) everything works as expected.

Not sure if this is a gem incompatibility - versions below:
gollum (3.1.2)
gollum-grit_adapter (0.1.3)
gollum-lib (4.0.2)
oauth2 (1.0.0)
omniauth (1.2.2)
omniauth-github (1.1.2)
omniauth-google-oauth2 (0.2.6)
omniauth-ldap (1.0.4)
omniauth-oauth2 (1.2.0)
omnigollum (0.1.4)
sinatra (1.4.5)
(Abridged list)

```
10.0.2.2 - - [10/Mar/2015:16:58:58 UTC] "GET /history/Home HTTP/1.1" 200 4688
http://localhost:9000/Home -> /history/Home
[2015-03-10 16:59:01] ERROR NoMethodError: undefined method `join' for #<String:0x00000001f90de8>
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
        /usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
10.0.2.2 - - [10/Mar/2015:16:59:01 UTC] "POST /compare/Home HTTP/1.1" 500 340
```

**Comment by dquenault** [comment]
Ah - found the other issue relating to this. Pushed the gollum gem back to v3.0.0 and everything returned back to normal

**Comment by arr2036** [comment]
See https://github.com/arr2036/omnigollum/issues/24
