### ISSUE TITLE
Integrate gollum with omnigollum

### ISSUE THREAD

**Issue by foodaka** [arr2036/omnigollum#36]
Hi, Ive got both gollum and omnigollum on my local machine. How do I integrate the two together? Or can I just run omnigollum?

**Comment by foodaka** [comment]
I have gollum up and running, but i'm not sure how to include omnigollum so I can get up an authorization with my internal wiki site. Do I edit the omnigollum config.rb files and then require 'omnigollum' in my config.ru of my gollum folder? As of now they are two seperate projects

**Comment by Geremia** [comment]
@foodaka Omnigollum = gollum + omniauth. Omnigollum is a fork of gollum. Just use Omnigollum.

**Comment by Geremia** [comment]
@foodaka I think you can just run Omnigollum. Omnigollum is a fork of Gollum.
