### ISSUE TITLE
Authorised Users Check

### ISSUE THREAD

**Issue by iTsFILIPOficial** [arr2036/omnigollum#39]
In the 

```
options[:authorized_users] = ["example0@example.org", "example1@example.org", "example2@example.org"]
```
Is there a option to have all user of a specific domain? For example do all users in @github.com can access the wiki while users with @example.org will not be able to do so.

Filipe

**Comment by BriceShatzer** [comment]
The ability to provide a Regex in lieu of an array was added with this [pull request](https://github.com/arr2036/omnigollum/pull/25).

This commit happened after the most recent version was released, so you'll have to clone and build the gem locally (demonstrated in [Readme](https://github.com/arr2036/omnigollum/blob/master/Readme.md)) in addition to including it in your gem file.

**Comment by arr2036** [comment]
Just pushed a new gem.

**Comment by iTsFILIPOficial** [comment]
@BriceShatzer Could you show a config example for a regex that take in everyone in a domain?

**Comment by BriceShatzer** [comment]
We use google as our provider, so the options object we use looks roughly like: 

```
options = {
  # OmniAuth::Builder block is passed as a proc
  :providers => Proc.new do
    provider :google_oauth2, "CONSUMER_KEY", "CONSUMER_SECRET"
  end,
  :authorized_users => /@bizname.com$/,
  :protected_routes => ['/*'],
  :dummy_auth => false
}

Precious::App.set(:omnigollum, options)
```

this prevents access to all pages unless the user authenticates with an email address that ends with the string "@bizname.com"

**Comment by iTsFILIPOficial** [comment]
@BriceShatzer Thank you that actually worked.

**Comment by iTsFILIPOficial** [comment]
@BriceShatzer Is there a way to have two domains?

**Comment by BriceShatzer** [comment]
you should be able to do: 
```
:authorized_users => /@bizname.com$|@company.com$/,
 ```

**Comment by iTsFILIPOficial** [comment]
@BriceShatzer Thank you
